config:
  notNotify: false
  commandWait: 1
  chatWait: 2
  chatLengthLimit: 64
  chatLimit: 8
  useRemote: true
  log: true
  dirtyList:
    - '你个fw'
    - '你个fvv'
  commandWhiteList:
    - '/spam'
    - '/l'
    - '/login'
    - '/r'
    - '/reg'
    - '/register'
  usePunishment: false
  spamLimit: 10
debug: false
